export const days = [
  { key: "mon", label: "Даваа" },
  { key: "tue", label: "Мягмар" },
  { key: "wed", label: "Лхагва" },
  { key: "thu", label: "Пүрэв" },
  { key: "fri", label: "Баасан" },
];

export const lessons = {
  cysec301: {
    name: "Цахим аюулгүй байдал",
    description: "Энэхүү хичээл нь Хэрэглэгчийн Интерфэйс (UI) болон...",
    groups: ["SE206-1", "SE206-2", "SE206-3", "CS210"],
    teacher: "Төгөлдөр",
    maxScores: [
      { label: "Ирц", score: 10 },
      { label: "Лаборатори", score: 20 },
      { label: "Бие даалт", score: 20 },
      { label: "Гэрийн даалгавар", score: 10 },
      { label: "Явцын шалгалт", score: 10 },
      { label: "Улиралын шалгалт", score: 30 },
    ],
    attendance: {
      lecture: [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0],
      laboratory: [1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0],
    },
    assignments: [
      {
        type: "Лаборатори",
        name: "Лаборатори 1: Оюутны хэрэгцээ тодорхойлох",
        dateRange: "2025/02/03 - 2025/02/24",
        score: 3,
        maxScore: 3,
      },
      {
        type: "Лаборатори",
        name: "Лаборатори 2: Багшийн хэрэгцээ тодорхойлох",
        dateRange: "2025/02/03 - 2025/02/24",
        score: 2,
        maxScore: 3,
      },
      {
        type: "Лаборатори",
        name: "Лаборатори 3: Багшийн хэрэгцээ тодорхойлох",
        dateRange: "2025/02/03 - 2025/02/24",
        score: 2.5,
        maxScore: 3,
      },
      {
        type: "Лаборатори",
        name: "Лаборатори 3: Багшийн хэрэгцээ тодорхойлох",
        dateRange: "2025/02/03 - 2025/02/24",
        score: null,
        maxScore: 3,
      },
      {
        type: "Бие даалт",
        name: "Бие даалт 1: ...",
        dateRange: "2025/02/03 - 2025/03/01",
        score: 9,
        maxScore: 10,
      },
    ],
    grades: [
      { label: "Ирц", score: 7, color: "#A8BEF0" },
      { label: "Бие даалт", score: 9, color: "#A8D8D0" },
      { label: "Лаборатори", score: 20, color: "#7B93C8" },
      { label: "Явцын шалгалт", score: 10, color: "#3D5A8A" },
      // { label: "Улиралын шалгалт", score: 24, color: "#6a8dc5ff" },
    ],
  },
  py302: {
    name: "Пайтон програмчлал ба өгөгдлийн шинжилгээ",
    grades: [
      { label: "Ирц", score: 10, color: "#A8BEF0" },
      { label: "Бие даалт", score: 10, color: "#A8D8D0" },
      { label: "Лаборатори", score: 20, color: "#7B93C8" },
      { label: "Явцын шалгалт", score: 10, color: "#3D5A8A" },
      // { label: "Улиралын шалгалт", score: 24, color: "#6a8dc5ff" },
    ],
    description: "Энэхүү хичээл нь Хэрэглэгчийн Интерфэйс (UI) болон...",
    groups: ["SE206-1", "SE206-2", "SE206-3", "CS210"],
    teacher: "Төгөлдөр",
    maxScores: [
      { label: "Ирц", score: 10 },
      { label: "Лаборатори", score: 20 },
      { label: "Бие даалт", score: 20 },
      { label: "Гэрийн даалгавар", score: 10 },
      { label: "Явцын шалгалт", score: 10 },
      { label: "Улиралын шалгалт", score: 30 },
    ],
    attendance: {
      lecture: [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0],
      laboratory: [1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0],
    },
    assignments: [
      {
        type: "Лаборатори",
        name: "Лаборатори 1: Оюутны хэрэгцээ тодорхойлох",
        dateRange: "2025/02/03 - 2025/02/24",
        score: 3,
      },
      {
        type: "Лаборатори",
        name: "Лаборатори 2: Багшийн хэрэгцээ тодорхойлох",
        dateRange: "2025/02/03 - 2025/02/24",
        score: 3,
      },
      {
        type: "Бие даалт",
        name: "Бие даалт 1: ...",
        dateRange: "2025/02/03 - 2025/03/01",
        score: 9,
      },
    ],
  },
  math303: {
    name: "Магадлал ба статистик",
    grades: [
      { label: "Ирц", score: 7, color: "#A8BEF0" },
      { label: "Бие даалт", score: 9, color: "#A8D8D0" },
      { label: "Лаборатори", score: 20, color: "#7B93C8" },
      { label: "Явцын шалгалт", score: 10, color: "#3D5A8A" },
      // { label: "Улиралын шалгалт", score: 24, color: "#6a8dc5ff" },
    ],
    description: "Энэхүү хичээл нь Хэрэглэгчийн Интерфэйс (UI) болон...",
    groups: ["SE206-1", "SE206-2", "SE206-3", "CS210"],
    teacher: "Төгөлдөр",
    maxScores: [
      { label: "Ирц", score: 10 },
      { label: "Лаборатори", score: 20 },
      { label: "Бие даалт", score: 20 },
      { label: "Гэрийн даалгавар", score: 10 },
      { label: "Явцын шалгалт", score: 10 },
      { label: "Улиралын шалгалт", score: 30 },
    ],
    attendance: {
      lecture: [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0],
      laboratory: [1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0],
    },
    assignments: [
      {
        type: "Лаборатори",
        name: "Лаборатори 1: Оюутны хэрэгцээ тодорхойлох",
        dateRange: "2025/02/03 - 2025/02/24",
        score: 3,
      },
      {
        type: "Лаборатори",
        name: "Лаборатори 2: Багшийн хэрэгцээ тодорхойлох",
        dateRange: "2025/02/03 - 2025/02/24",
        score: 3,
      },
      {
        type: "Бие даалт",
        name: "Бие даалт 1: ...",
        dateRange: "2025/02/03 - 2025/03/01",
        score: 9,
      },
    ],
  },
  ai304: {
    name: "Хиймэл оюун ухааны үндэс ба машин сургалт",
    grades: [
      { label: "Ирц", score: 7, color: "#A8BEF0" },
      { label: "Бие даалт", score: 9, color: "#A8D8D0" },
      { label: "Лаборатори", score: 20, color: "#7B93C8" },
      { label: "Явцын шалгалт", score: 10, color: "#3D5A8A" },
      // { label: "Улиралын шалгалт", score: 24, color: "#6a8dc5ff" },
    ],
    description: "Энэхүү хичээл нь Хэрэглэгчийн Интерфэйс (UI) болон...",
    groups: ["SE206-1", "SE206-2", "SE206-3", "CS210"],
    teacher: "Төгөлдөр",
    maxScores: [
      { label: "Ирц", score: 10 },
      { label: "Лаборатори", score: 20 },
      { label: "Бие даалт", score: 20 },
      { label: "Гэрийн даалгавар", score: 10 },
      { label: "Явцын шалгалт", score: 10 },
      { label: "Улиралын шалгалт", score: 30 },
    ],
    attendance: {
      lecture: [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0],
      laboratory: [1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0],
    },
    assignments: [
      {
        type: "Лаборатори",
        name: "Лаборатори 1: Оюутны хэрэгцээ тодорхойлох",
        dateRange: "2025/02/03 - 2025/02/24",
        score: 3,
      },
      {
        type: "Лаборатори",
        name: "Лаборатори 2: Багшийн хэрэгцээ тодорхойлох",
        dateRange: "2025/02/03 - 2025/02/24",
        score: 3,
      },
      {
        type: "Бие даалт",
        name: "Бие даалт 1: ...",
        dateRange: "2025/02/03 - 2025/03/01",
        score: 9,
      },
    ],
  },
  net305: {
    name: "Компьютерийн сүлжээ",
    grades: [
      { label: "Ирц", score: 7, color: "#A8BEF0" },
      { label: "Бие даалт", score: 9, color: "#A8D8D0" },
      { label: "Лаборатори", score: 20, color: "#7B93C8" },
      { label: "Явцын шалгалт", score: 10, color: "#3D5A8A" },
      // { label: "Улиралын шалгалт", score: 24, color: "#6a8dc5ff" },
    ],
    description: "Энэхүү хичээл нь Хэрэглэгчийн Интерфэйс (UI) болон...",
    groups: ["SE206-1", "SE206-2", "SE206-3", "CS210"],
    teacher: "Төгөлдөр",
    maxScores: [
      { label: "Ирц", score: 10 },
      { label: "Лаборатори", score: 20 },
      { label: "Бие даалт", score: 20 },
      { label: "Гэрийн даалгавар", score: 10 },
      { label: "Явцын шалгалт", score: 10 },
      { label: "Улиралын шалгалт", score: 30 },
    ],
    attendance: {
      lecture: [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0],
      laboratory: [1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0],
    },
    assignments: [
      {
        type: "Лаборатори",
        name: "Лаборатори 1: Оюутны хэрэгцээ тодорхойлох",
        dateRange: "2025/02/03 - 2025/02/24",
        score: 3,
      },
      {
        type: "Лаборатори",
        name: "Лаборатори 2: Багшийн хэрэгцээ тодорхойлох",
        dateRange: "2025/02/03 - 2025/02/24",
        score: 3,
      },
      {
        type: "Бие даалт",
        name: "Бие даалт 1: ...",
        dateRange: "2025/02/03 - 2025/03/01",
        score: 9,
      },
    ],
  },
  mob306: {
    name: "Мобайл програмчлал",
    grades: [
      { label: "Ирц", score: 7, color: "#A8BEF0" },
      { label: "Бие даалт", score: 9, color: "#A8D8D0" },
      { label: "Лаборатори", score: 20, color: "#7B93C8" },
      { label: "Явцын шалгалт", score: 10, color: "#3D5A8A" },
      // { label: "Улиралын шалгалт", score: 24, color: "#6a8dc5ff" },
    ],
    description: "Энэхүү хичээл нь Хэрэглэгчийн Интерфэйс (UI) болон...",
    groups: ["SE206-1", "SE206-2", "SE206-3", "CS210"],
    teacher: "Төгөлдөр",
    maxScores: [
      { label: "Ирц", score: 10 },
      { label: "Лаборатори", score: 20 },
      { label: "Бие даалт", score: 20 },
      { label: "Гэрийн даалгавар", score: 10 },
      { label: "Явцын шалгалт", score: 10 },
      { label: "Улиралын шалгалт", score: 30 },
    ],
    attendance: {
      lecture: [1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0],
      laboratory: [1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0],
    },
    assignments: [
      {
        type: "Лаборатори",
        name: "Лаборатори 1: Оюутны хэрэгцээ тодорхойлох",
        dateRange: "2025/02/03 - 2025/02/24",
        score: 3,
      },
      {
        type: "Лаборатори",
        name: "Лаборатори 2: Багшийн хэрэгцээ тодорхойлох",
        dateRange: "2025/02/03 - 2025/02/24",
        score: 3,
      },
      {
        type: "Бие даалт",
        name: "Бие даалт 1: ...",
        dateRange: "2025/02/03 - 2025/03/01",
        score: 9,
      },
    ],
  },
};

export const schedule = {
  mon: [
    {
      time: "10:00-11:30",
      subject: "Цахим аюулгүй байдал",
      type: "лекц",
      room: "ШМТИС 809",
      teacher: "Төгөлдөр",
      attendance: {
        lecture: [1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1],
        laboratory: [1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1],
        seminar: [],
      },
    },
    {
      time: "11:40-13:10",
      subject: "Мобайл програмчлал",
      type: "лекц",
      room: "ШМТИС 809",
      teacher: "Ц.Солонгоо",
      attendance: {
        lecture: [1, 1, 0, 1, 1, 1, 0, 1],
        laboratory: [1, 0, 1, 1, 1, 0, 1, 1],
        seminar: [1, 1, 0, 1, 0, 0, 1, 1],
      },
    },
    {
      time: "14:00-15:30",
      subject: "Пайтон програмчлал ба өгөгдлийн шинжилгээ",
      type: "лаборатор",
      room: "ШМТИС 913",
      teacher: "Ц.Солонгоо",
      attendance: {
        lecture: [1, 1, 0, 1, 1, 1, 0, 1],
        laboratory: [1, 0, 1, 1, 1, 0, 1, 1],
        seminar: [],
      },
    },
    {
      time: "15:40-17:10",
      subject: "Цахим аюулгүй байдал",
      type: "лаборатор",
      room: "ШМТИС 913",
      teacher: "Төгөлдөр",
      attendance: {
        lecture: [1, 1, 0, 1, 1, 1, 0, 1],
        laboratory: [1, 0, 1, 1, 1, 0, 1, 1],
        seminar: [],
      },
    },
  ],
  tue: [],
  wed: [
    {
      time: "8:20-9:50",
      subject: "Мобайл програмчлал",
      type: "лаборатор",
      room: "ШМТИС 913",
      teacher: "Ц.Солонгоо",
      attendance: {
        lecture: [1, 1, 0, 1, 1, 1, 0, 1],
        laboratory: [1, 0, 1, 1, 1, 0, 1, 1],
        seminar: [],
      },
    },
    {
      time: "10:00-11:30",
      subject: "Хиймэл оюун ухааны үндэс ба машин сургалт",
      type: "лекц",
      room: "ШМТИС 711",
      teacher: "Н.Анхбаяр",
      attendance: {
        lecture: [1, 1, 0, 1, 1, 1, 0, 1],
        laboratory: [1, 0, 1, 1, 1, 0, 1, 1],
        seminar: [],
      },
    },
    {
      time: "11:40-13:10",
      subject: "Магадлал ба статистик",
      type: "семинар",
      room: "ШМТИС 712",
      teacher: "Б.Санчир",
      attendance: {
        lecture: [1, 1, 0, 1, 1, 1, 0, 1],
        laboratory: [1, 0, 1, 1, 1, 0, 1, 1],
        seminar: [],
      },
    },
    {
      time: "14:00-15:30",
      subject: "Магадлал ба статистик",
      type: "лекц",
      room: "ШМТИС 711",
      teacher: "Б.Санчир",
      attendance: {
        lecture: [1, 1, 0, 1, 1, 1, 0, 1],
        laboratory: [1, 0, 1, 1, 1, 0, 1, 1],
        seminar: [],
      },
    },
  ],
  thu: [],
  fri: [
    {
      time: "8:20-9:50",
      subject: "Пайтон програмчлал ба өгөгдлийн шинжилгээ",
      type: "лекц",
      room: "ШМТИС 913",
      teacher: "Ц.Солонгоо",
      attendance: {
        lecture: [1, 1, 0, 1, 1, 1, 0, 1],
        laboratory: [1, 0, 1, 1, 1, 0, 1, 1],
        seminar: [],
      },
    },
    {
      time: "10:00-11:30",
      subject: "Компьютерийн сүлжээ",
      type: "лекц",
      room: "ШМТИС 809",
      teacher: "Б.Ганзориг",
      attendance: {
        lecture: [1, 1, 0, 1, 1, 1, 0, 1],
        laboratory: [1, 0, 1, 1, 1, 0, 1, 1],
        seminar: [],
      },
    },
    {
      time: "11:40-13:10",
      subject: "Компьютерийн сүлжээ",
      type: "лаборатор",
      room: "ШМТИС 913",
      teacher: "Б.Ганзориг",
      attendance: {
        lecture: [1, 1, 0, 1, 1, 1, 0, 1],
        laboratory: [1, 0, 1, 1, 1, 0, 1, 1],
        seminar: [],
      },
    },
    {
      time: "14:00-15:30",
      subject: "Хиймэл оюун ухааны үндэс ба машин сургалт",
      type: "лаборатор",
      room: "ШМТИС 912",
      teacher: "Н.Анхбаяр",
      attendance: {
        lecture: [1, 1, 0, 1, 1, 1, 0, 1],
        laboratory: [1, 0, 1, 1, 1, 0, 1, 1],
        seminar: [],
      },
    },
  ],
};
